; Script generated by Cypher AI for Professional Deployment
; This script requires Inno Setup (https://jrsoftware.org/isdl.php)

[Setup]
AppId={{D3A5F6E8-4B2C-4E1D-9A7F-E8D9C0B1A2D3}}
AppName=CYPHER
AppVersion=1.0.0
AppPublisher=Emerald Dev
AppPublisherURL=https://linktr.ee/Emerald_dev
AppSupportURL=https://tiktok.com/@emerald_dev1
AppUpdatesURL=https://tiktok.com/@emerald_dev1

; Professional Deployment: Install to Local AppData to avoid UAC / Admin issues
DefaultDirName={localappdata}\CYPHER
DefaultGroupName=CYPHER
AllowNoIcons=yes

; [FIX] Auto-close old version before updating
CloseApplications=yes
RestartApplications=yes
AppMutex=CypherAppMutex_D3A5F6E8

; The following line specifies where to save the generated setup.exe
OutputDir=dist\installer
OutputBaseFilename=Cypher_Setup_v1.0.0
Compression=lzma
SolidCompression=yes
WizardStyle=modern

; SECURITY & TRUST: Avoid mandatory admin unless absolutely necessary
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
UninstallDisplayIcon={app}\cypher.exe
SetupIconFile=icon.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startup"; Description: "Launch CYPHER on Windows Startup"; GroupDescription: "Auto-Launch:"; Flags: unchecked

[Files]
; IMPORTANT: Source points to the 'dist/cypher.exe' generated by PyInstaller
Source: "dist\cypher.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "icon.ico"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\CYPHER"; Filename: "{app}\cypher.exe"; IconFilename: "{app}\icon.ico"
Name: "{autodesktop}\CYPHER"; Filename: "{app}\cypher.exe"; Tasks: desktopicon; IconFilename: "{app}\icon.ico"
Name: "{userstartup}\CYPHER"; Filename: "{app}\cypher.exe"; Tasks: startup; IconFilename: "{app}\icon.ico"

[Run]
Filename: "{app}\cypher.exe"; Description: "{cm:LaunchProgram,CYPHER}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Clean removal: Delete the entire app folder and all its persistent data (settings, logs, paired devices)
Type: filesandordirs; Name: "{app}"
Type: filesandordirs; Name: "{localappdata}\CYPHER"
