; Script generated by Cypher AI for Industry Standard Deployment
; REQUIRES: Inno Setup (https://jrsoftware.org/isdl.php)

[Setup]
AppId={{C9PHER-BC12-4E8F-A9D1-789456123456}
AppName=CYPHER
AppVersion=1.0.0
AppPublisher=Emerald Dev
AppPublisherURL=https://tiktok.com/@emerald_dev1
AppSupportURL=https://tiktok.com/@emerald_dev1
AppUpdatesURL=https://tiktok.com/@emerald_dev1
DefaultDirName={autopf}\CYPHER
DisableDirPage=yes
DefaultGroupName=CYPHER
AllowNoIcons=yes
; The following line specifies the location of the PyInstaller output
OutputDir=dist\installer
OutputBaseFilename=Cypher_Setup_v1.0.0
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin
SetupIconFile=..\mobile_app\assets\icon\icon.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startup"; Description: "Launch CYPHER on Windows Startup"; GroupDescription: "Auto-Launch:"; Flags: unchecked

[Files]
; IMPORTANT: Path points to the 'dist/cypher' folder generated by PyInstaller --onefile
Source: "dist\cypher.exe"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\CYPHER"; Filename: "{app}\cypher.exe"
Name: "{autodesktop}\CYPHER"; Filename: "{app}\cypher.exe"; Tasks: desktopicon
Name: "{userstartup}\CYPHER"; Filename: "{app}\cypher.exe"; Tasks: startup

[Run]
Filename: "{app}\cypher.exe"; Description: "{cm:LaunchProgram,CYPHER}"; Flags: nowait postinstall skipifsilent
