; Script generated by Cypher AI for Industry Standard Deployment
; REQUIRES: Inno Setup (https://jrsoftware.org/isdl.php)

[Setup]
AppId={{C9PHER-BC12-4E8F-A9D1-789456123456}
AppName=CYPHER
AppVersion=1.0.0
AppPublisher=Emerald Dev
DefaultDirName={autopf}\CYPHER
DisableDirPage=yes
DefaultGroupName=CYPHER
AllowNoIcons=yes
OutputDir=dist\installer
OutputBaseFilename=Cypher_Setup_v1.0.0
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; Installer runs as Admin to set up system-wide permissions
PrivilegesRequired=admin
SetupIconFile=..\mobile_app\assets\icon\icon.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "startup"; Description: "Launch CYPHER on Windows Startup"; GroupDescription: "Auto-Launch:"; Flags: unchecked

[Files]
Source: "dist\cypher.exe"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\CYPHER"; Filename: "{app}\cypher.exe"
Name: "{autodesktop}\CYPHER"; Filename: "{app}\cypher.exe"; Tasks: desktopicon
Name: "{userstartup}\CYPHER"; Filename: "{app}\cypher.exe"; Tasks: startup

[Registry]
; [LUXURY FIX] This registry key tells Windows to always grant this app Admin rights without prompting again
Root: "HKLM"; Subkey: "SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers"; \
    ValueType: String; ValueName: "{app}\cypher.exe"; ValueData: "~ RUNASADMIN"; Flags: uninsdeletevalue

[Run]
; Run the firewall configuration silently during setup
Filename: "netsh"; Parameters: "advfirewall firewall add rule name=""CYPHER_BRIDGE"" dir=in action=allow protocol=TCP localport=5000,5001"; Flags: runhidden
Filename: "netsh"; Parameters: "advfirewall firewall add rule name=""CYPHER_DISCOVERY"" dir=in action=allow protocol=UDP localport=5001,5002"; Flags: runhidden
; Final launch
Filename: "{app}\cypher.exe"; Description: "{cm:LaunchProgram,CYPHER}"; Flags: nowait postinstall skipifsilent
